spring.application.name=Pre-Transfer
server.port = 8080
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=mongo-ptp
spring.data.mongodb.uri=mongodb://mongoadmin:mongoadmin@localhost:27017/mongo-ptp?authSource=admin&retryWrites=true&w=majority
